# Licensed under BSL 1.1 — commercial use requires written permission
# Change date: 2027-01-01 to MIT License by Bhupen Nayak
# Contact: askzachn@gmail.com

"""
Brahman Sovereign Node — Solnet Mesh RPC Wrapper

Exposes the Brahman Kernel as a network-accessible verification node.
When a transaction or synthesis request hits the Solnet P2P mesh, it
is routed to this node. The pipeline:

    1. Receive payload via HTTP/WebSocket
    2. MLX Qwen translates raw input → Kāraka Protocol JSON
    3. Brahman Kernel verifies against loaded Sūtra cartridge
    4. Node broadcasts cryptographically signed Verdict + Logic Hash

If a malicious node tries to spoof a "VALID" hash, the cryptographic
signature fails because it cannot forge the mathematical proof
generated by the Sūtra traversal.

Endpoints:
    POST /verify         — Raw text + domain → Verdict
    POST /verify/kp      — Pre-built Kāraka Protocol → Verdict
    GET  /cartridges     — List available Sūtra cartridges
    POST /cartridge/load — Hot-swap a cartridge
    GET  /health         — Node health + loaded domain
    WS   /ws/verify      — WebSocket for streaming verification
"""

import os
import json
import time
import hashlib
import asyncio
from pathlib import Path
from typing import Optional, List, Dict
from contextlib import asynccontextmanager
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException, Depends, Security, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, Field

import sys
sys.path.insert(0, str(Path(__file__).parent))
from brahman_kernel import BrahmanKernel, Verdict, VerificationResult


# ══════════════════════════════════════════════════════════════════
# NODE CONFIGURATION
# ══════════════════════════════════════════════════════════════════

NODE_ID = os.environ.get("BRAHMAN_NODE_ID", f"sovereign-{hashlib.sha256(os.urandom(8)).hexdigest()[:8]}")

API_KEY = os.environ.get("BRAHMAN_API_KEY", "brahman-dev-secret-key-123")
api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)

async def get_api_key(api_key_header: str = Security(api_key_header)):
    if api_key_header == API_KEY:
        return api_key_header
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid or missing API Key"
    )
CARTRIDGE_DIR = Path(__file__).parent / "cartridges"
DEFAULT_CARTRIDGE = "sanskrit_sutras.json"

# Global state
kernel = BrahmanKernel()
translator = None  # Lazy-loaded MLX translator
node_start_time = time.time()
request_count = 0
verified_count = {"VALID": 0, "INVALID": 0, "AMBIGUOUS": 0}


# ══════════════════════════════════════════════════════════════════
# PYDANTIC MODELS
# ══════════════════════════════════════════════════════════════════

class VerifyRequest(BaseModel):
    raw_input: str = Field(..., description="Raw text to verify")
    domain: str = Field("general", description="Domain hint for the MLX translator")
    use_mlx: bool = Field(True, description="Use MLX neural translator (False = manual KP)")

class KPVerifyRequest(BaseModel):
    karaka_protocol: dict = Field(..., description="Pre-built Kāraka Protocol JSON")

class LoadCartridgeRequest(BaseModel):
    cartridge: str = Field(..., description="Cartridge filename (e.g., 'rust_crypto_sutras.json')")

class VerifyResponse(BaseModel):
    node_id: str
    verdict: str
    violations: List[str]
    matched_sutras: List[str]
    dhatu_found: bool
    logic_hash: str
    domain: str
    processing_time_ms: float
    timestamp: float

class NodeHealth(BaseModel):
    node_id: str
    status: str
    loaded_domain: str
    uptime_seconds: float
    total_requests: int
    verdicts: Dict[str, int]
    available_cartridges: List[str]
    mlx_loaded: bool


# ══════════════════════════════════════════════════════════════════
# APP LIFECYCLE
# ══════════════════════════════════════════════════════════════════

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: Load default cartridge
    default_path = CARTRIDGE_DIR / DEFAULT_CARTRIDGE
    if default_path.exists():
        msg = kernel.load_cartridge(str(default_path))
        print(f"[{NODE_ID}] {msg}")
    print(f"[{NODE_ID}] Sovereign Node online.")
    yield
    # Shutdown
    print(f"[{NODE_ID}] Node shutting down. Verified {sum(verified_count.values())} transactions.")


app = FastAPI(
    title="Brahman Sovereign Node",
    description="Deterministic neuro-symbolic verification node for the Solnet P2P mesh.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ══════════════════════════════════════════════════════════════════
# ENDPOINTS
# ══════════════════════════════════════════════════════════════════

@app.get("/health", response_model=NodeHealth, dependencies=[Depends(get_api_key)])
async def health():
    """Node health check — returns status, loaded domain, and statistics."""
    cartridges = [f.name for f in CARTRIDGE_DIR.glob("*.json")]
    return NodeHealth(
        node_id=NODE_ID,
        status="online",
        loaded_domain=kernel.loaded_domain,
        uptime_seconds=round(time.time() - node_start_time, 1),
        total_requests=request_count,
        verdicts=verified_count,
        available_cartridges=sorted(cartridges),
        mlx_loaded=translator is not None and translator._loaded,
    )


@app.get("/cartridges", dependencies=[Depends(get_api_key)])
async def list_cartridges():
    """List all available Sūtra cartridges."""
    cartridges = []
    for f in sorted(CARTRIDGE_DIR.glob("*.json")):
        data = json.loads(f.read_text(encoding="utf-8"))
        cartridges.append({
            "filename": f.name,
            "domain": data.get("domain"),
            "version": data.get("version"),
            "description": data.get("description", ""),
            "sutras_count": len(data.get("sutras", [])),
            "roots_count": len(data.get("root_lexicon", {})),
        })
    return {"cartridges": cartridges, "loaded": kernel.loaded_domain}


@app.post("/cartridge/load", dependencies=[Depends(get_api_key)])
async def load_cartridge(req: LoadCartridgeRequest):
    """Hot-swap a Sūtra cartridge at runtime."""
    path = CARTRIDGE_DIR / req.cartridge
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Cartridge '{req.cartridge}' not found.")
    msg = kernel.load_cartridge(str(path))
    return {"status": "loaded", "message": msg, "domain": kernel.loaded_domain}


@app.post("/verify", response_model=VerifyResponse, dependencies=[Depends(get_api_key)])
async def verify_text(req: VerifyRequest):
    """
    Verify raw text through the full pipeline:
    Raw Text → MLX Translation → Kernel Verification → Signed Verdict
    """
    global request_count, translator
    request_count += 1
    start = time.time()

    if req.use_mlx:
        # Lazy-load the MLX translator on first use
        if translator is None:
            from mlx_translator import MLXTranslator
            translator = MLXTranslator(domain=req.domain)
            translator.load()

        kp = translator.translate(req.raw_input, domain=req.domain)
    else:
        # Minimal KP fallback (no neural translation)
        kp = kernel.evaluate(req.raw_input).to_dict()
        # Re-verify via full path
        result = kernel.evaluate(req.raw_input)
        elapsed = (time.time() - start) * 1000
        verified_count[result.verdict] = verified_count.get(result.verdict, 0) + 1
        return VerifyResponse(
            node_id=NODE_ID,
            verdict=result.verdict,
            violations=result.violations,
            matched_sutras=result.matched_sutras,
            dhatu_found=result.dhatu_found,
            logic_hash=result.logic_hash,
            domain=kernel.loaded_domain,
            processing_time_ms=round(elapsed, 1),
            timestamp=time.time(),
        )

    result = kernel.verify(kp)
    elapsed = (time.time() - start) * 1000
    verified_count[result.verdict] = verified_count.get(result.verdict, 0) + 1

    return VerifyResponse(
        node_id=NODE_ID,
        verdict=result.verdict,
        violations=result.violations,
        matched_sutras=result.matched_sutras,
        dhatu_found=result.dhatu_found,
        logic_hash=result.logic_hash,
        domain=kernel.loaded_domain,
        processing_time_ms=round(elapsed, 1),
        timestamp=time.time(),
    )


@app.post("/verify/kp", response_model=VerifyResponse, dependencies=[Depends(get_api_key)])
async def verify_kp(req: KPVerifyRequest):
    """
    Verify a pre-built Kāraka Protocol instance directly.
    Bypasses the neural translator — pure symbolic verification.
    """
    global request_count
    request_count += 1
    start = time.time()

    result = kernel.verify(req.karaka_protocol)
    elapsed = (time.time() - start) * 1000
    verified_count[result.verdict] = verified_count.get(result.verdict, 0) + 1

    return VerifyResponse(
        node_id=NODE_ID,
        verdict=result.verdict,
        violations=result.violations,
        matched_sutras=result.matched_sutras,
        dhatu_found=result.dhatu_found,
        logic_hash=result.logic_hash,
        domain=kernel.loaded_domain,
        processing_time_ms=round(elapsed, 1),
        timestamp=time.time(),
    )


# ══════════════════════════════════════════════════════════════════
# WEBSOCKET — Streaming Verification
# ══════════════════════════════════════════════════════════════════

@app.websocket("/ws/verify")
async def ws_verify(websocket: WebSocket):
    """
    WebSocket endpoint for streaming verification.
    Send JSON: {"raw_input": "...", "domain": "..."} and receive
    the verdict back in real-time. Keeps the connection alive for
    continuous mesh operation.
    """
    await websocket.accept()
    print(f"[{NODE_ID}] WebSocket client connected.")

    try:
        while True:
            data = await websocket.receive_json()
            raw_input = data.get("raw_input", "")
            domain = data.get("domain", kernel.loaded_domain)

            global request_count
            request_count += 1
            start = time.time()

            # Use kernel's evaluate for WS (no MLX overhead per message)
            result = kernel.evaluate(raw_input)
            elapsed = (time.time() - start) * 1000
            verified_count[result.verdict] = verified_count.get(result.verdict, 0) + 1

            await websocket.send_json({
                "node_id": NODE_ID,
                "verdict": result.verdict,
                "violations": result.violations,
                "logic_hash": result.logic_hash,
                "processing_time_ms": round(elapsed, 1),
                "timestamp": time.time(),
            })
    except WebSocketDisconnect:
        print(f"[{NODE_ID}] WebSocket client disconnected.")


# ══════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("BRAHMAN_PORT", 8420))
    print(f"\n{'='*60}")
    print(f"  BRAHMAN SOVEREIGN NODE")
    print(f"  Node ID: {NODE_ID}")
    print(f"  Port:    {port}")
    print(f"  Cartridges: {CARTRIDGE_DIR}")
    print(f"{'='*60}\n")
    uvicorn.run(app, host="0.0.0.0", port=port)
